apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "orchestration-scaling-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{- with .Values.ingress.hosts.host }}
      http:
        paths:
          - path: {{- with .Values.ingress.hosts.paths.path }}
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  number: 3001
          - path: /profile
            pathType: Prefix
            backend:
              service:
                name: profile-service
                port:
                  number: 3002
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-frontend-app
                port:
                  number: {{- with .Values.ingress.podAnnotations }}
