apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestration-scaling-chart.fullname" . }}-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
