apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "orchestration-scaling-chart.fullname" . }}-hello-ingress
spec:
  rules:
    - host: hello.cloudcrypto.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "orchestration-scaling-chart.fullname" . }}-hello-service
                port:
                  number: 80
